/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ExistingFormImport } from './routes/existing-form'
import { Route as AboutImport } from './routes/about'
import { Route as ControllerImport } from './routes/Controller'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const ExistingFormRoute = ExistingFormImport.update({
  id: '/existing-form',
  path: '/existing-form',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const ControllerRoute = ControllerImport.update({
  id: '/Controller',
  path: '/Controller',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/Controller': {
      id: '/Controller'
      path: '/Controller'
      fullPath: '/Controller'
      preLoaderRoute: typeof ControllerImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/existing-form': {
      id: '/existing-form'
      path: '/existing-form'
      fullPath: '/existing-form'
      preLoaderRoute: typeof ExistingFormImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Controller': typeof ControllerRoute
  '/about': typeof AboutRoute
  '/existing-form': typeof ExistingFormRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Controller': typeof ControllerRoute
  '/about': typeof AboutRoute
  '/existing-form': typeof ExistingFormRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/Controller': typeof ControllerRoute
  '/about': typeof AboutRoute
  '/existing-form': typeof ExistingFormRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/Controller' | '/about' | '/existing-form'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/Controller' | '/about' | '/existing-form'
  id: '__root__' | '/' | '/Controller' | '/about' | '/existing-form'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ControllerRoute: typeof ControllerRoute
  AboutRoute: typeof AboutRoute
  ExistingFormRoute: typeof ExistingFormRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ControllerRoute: ControllerRoute,
  AboutRoute: AboutRoute,
  ExistingFormRoute: ExistingFormRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/Controller",
        "/about",
        "/existing-form"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/Controller": {
      "filePath": "Controller.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/existing-form": {
      "filePath": "existing-form.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
